### ISSUE TITLE
Second digital pulse output 

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/NidaqServer#1]
Hi Michael,
We need to give out a TTL pulse to drive an LED. We will use this to synchronize the timing of our webcams to the task timings. To make this simple we won't necessarily need to change the length of the TTL pulse, it could be fixed at about 100ms. 
We're using PCIe-6321.

Should I help with this? Any more information you need?

We will only need this feature in roughly 2 months time.
Thanks for your help!
Best,
Katharine

**Comment by Michael-Stephan** [comment]
Version 1.0.11.0 allows to configure additional lines of port 2 to output digital pulse signals.
